// AUTH
export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const CLEAN_STATE = 'CLEAN_STATE'

export const GET_PROFILE = 'LOGIN'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL'

export const SET_TOKEN_SUCCESS = 'SET_TOKEN_SUCCESS'
export const SET_TOKEN_FAILED = 'SET_TOKEN_FAILED'

export const OPEN_TOAST = 'OPEN_TOAST'
export const CLEAN_APP_STATE = 'CLEAN_APP_STATE'

// CATEGORY
export const GET_ALL_APP_PARAMS_SUCCESS = 'GET_ALL_APP_PARAMS_SUCCESS'
export const GET_ALL_APP_PARAMS_FAILED = 'GET_ALL_APP_PARAMS_FAILED'

// SHOP
export const GET_SHOP_INFO = 'GET_SHOP_INFO'
